# Generated by Django 3.1.4 on 2021-11-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
